Backendwithsf/force-app/main/default/objects/Dmart_User__c/Dmart_User__c.object-meta.xml
<CustomObject>
    <label>Dmart User</label>
    <nameField>
        <label>Dmart User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dmart Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Backendwithsf/force-app/main/default/objects/Dmart_User__c/fields/Firebase_UID__c.field-meta.xml
<CustomField>
    <fullName>Firebase_UID__c</fullName>
    <label>Firebase UID</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

Backendwithsf/force-app/main/default/classes/DMartUserAPI.cls
@RestResource(urlMapping='/dmart/user')
global with sharing class DMartUserAPI {

    @HttpPost
    global static String createUser() {

        RestRequest req = RestContext.request;
        String body = req.requestBody.toString();

        Map<String, Object> data = 
            (Map<String, Object>) JSON.deserializeUntyped(body);

        String name = (String) data.get('name');
        String email = (String) data.get('email');
        String phone = (String) data.get('phone');
        String uid = (String) data.get('uid');

        DMart_User__c user = new DMart_User__c(
            Name = name,
            Email__c = email,
            Phone__c = phone,
            Firebase_UID__c = uid
        );

        insert user;

        return 'User Created';
    }

    @HttpGet
    global static DMart_User__c getUser() {

        String uid = RestContext.request.params.get('uid');

        return [
            SELECT Id, Name, Email__c, Phone__c
            FROM DMart_User__c
            WHERE Firebase_UID__c = :uid
            LIMIT 1
        ];
    }
}