Backendwithsf/force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Backendwithsf/force-app/main/default/objects/Product__c/fields/Stock__c.field-meta.xml
<CustomField>
    <fullName>Stock__c</fullName>
    <label>Stock</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Backendwithsf/force-app/main/default/classes/DmartProductAPI.cls
@RestResource(urlMapping='/dmart/products')
global with sharing class DmartProductAPI {

    @HttpGet
    global static List<Product__c> getProducts() {
        return [SELECT Id, Name, Price__c, Stock__c, Image_URL__c FROM Product__c];
    }

    @HttpPost
    global static String addProduct() {
        RestRequest req = RestContext.request;
        String body = req.requestBody.toString();
        Product__c p = (Product__c) JSON.deserialize(body, Product__c.class);
        insert p;
        return 'Product Added Successfully';
    }
}